### ISSUE TITLE
The build process failed

### ISSUE THREAD

**Issue by ywgrit** [caojoshua/LLLVM#1]

**Comment by caojoshua** [comment]
English pls

**Comment by ywgrit** [comment]
In TailRecursionEliminationPass::elimTailCall, accessing BasicBlock's private member function getInstList, the build failed.
![image](https://github.com/user-attachments/assets/3fd02e4c-7450-4456-937c-339853262549)

**Comment by caojoshua** [comment]
Looks like you are on LLVM16. This project requires LLVM13. See https://github.com/caojoshua/LLLVM?tab=readme-ov-file#requirements

**Comment by ywgrit** [comment]
> Looks like you are on LLVM16. This project requires LLVM13. See https://github.com/caojoshua/LLLVM?tab=readme-ov-file#requirements

Thanks.
